language: ruby
branches:
  only:
  - master
sudo: false
rvm:
  - 2.3.1
  - 2.5.3
cache: bundler
bundler_args: "--jobs=3 --retry=3 --without production"
matrix:
  fast_finish: true
script:
  - bundle exec rubocop
  - COVERAGE=1 bundle exec rspec
